"""
Search configuration — covers all 4 hackathon domains plus broad biology.
Designed to produce thousands of entries across all sources.
"""

DOMAINS = ["cell_biology", "gut_health", "diagnostics", "climate"]

EXPERIMENT_TYPE_MAP = {
    "cell_biology": "in_vitro",
    "gut_health": "in_vivo",
    "diagnostics": "electrochemical",
    "climate": "microbial",
    "genomics": "in_vitro",
    "proteomics": "in_vitro",
    "immunology": "in_vitro",
    "microbiology": "microbial",
    "neuroscience": "in_vivo",
}

# ── Reagent search queries per domain ───────────────────────────────────────

REAGENT_QUERIES = {
    "cell_biology": [
        "trehalose cryoprotectant",
        "DMSO cell culture grade",
        "FBS fetal bovine serum",
        "trypan blue exclusion dye",
        "DMEM Dulbecco medium",
        "RPMI 1640 medium",
        "PBS phosphate buffered saline",
        "trypsin EDTA dissociation",
        "penicillin streptomycin antibiotic",
        "L-glutamine supplement",
        "MEM non-essential amino acids",
        "sodium pyruvate cell culture",
        "HEPES buffer cell culture",
        "crystal violet staining",
        "propidium iodide viability",
        "annexin V apoptosis",
        "BrdU proliferation assay",
        "MTT cell viability assay",
        "Matrigel basement membrane",
        "fibronectin cell attachment",
        "collagen type I coating",
        "Lipofectamine transfection",
        "Opti-MEM reduced serum",
        "puromycin selection",
        "blasticidin selection",
        "G418 geneticin selection",
        "hygromycin B selection",
    ],
    "gut_health": [
        "FITC dextran 4kDa permeability",
        "claudin-1 antibody tight junction",
        "occludin antibody junction",
        "ZO-1 antibody zonula occludens",
        "E-cadherin antibody epithelial",
        "Lactobacillus rhamnosus GG probiotic",
        "Bifidobacterium longum probiotic",
        "ELISA IL-6 mouse cytokine",
        "ELISA TNF-alpha mouse",
        "ELISA IL-1beta inflammation",
        "LPS lipopolysaccharide challenge",
        "Evans blue permeability dye",
        "colon tissue embedding paraffin",
        "hematoxylin eosin staining",
        "alcian blue mucus staining",
        "short chain fatty acid SCFA",
        "butyrate sodium supplement",
        "inulin prebiotic fiber",
        "16S rRNA sequencing gut",
        "germ-free mouse colonization",
    ],
    "diagnostics": [
        "anti-CRP C-reactive protein antibody",
        "screen printed carbon electrode",
        "gold nanoparticle AuNP synthesis",
        "nafion membrane biosensor coating",
        "EDC NHS coupling chemistry",
        "BSA blocking agent biosensor",
        "streptavidin biotin conjugation",
        "potassium ferricyanide redox mediator",
        "differential pulse voltammetry",
        "cyclic voltammetry electrochemical",
        "impedance spectroscopy EIS",
        "carbon nanotube electrode modification",
        "graphene oxide electrode",
        "nitrocellulose membrane lateral flow",
        "colloidal gold conjugation",
        "sandwich ELISA kit CRP",
        "microfluidic PDMS chip",
        "SU-8 photolithography",
        "HRP horseradish peroxidase",
        "alkaline phosphatase substrate",
        "TMB tetramethylbenzidine substrate",
    ],
    "climate": [
        "Sporomusa ovata anaerobic culture",
        "graphite felt biocathode electrode",
        "titanium wire current collector",
        "bicarbonate buffer CO2 saturated",
        "potassium phosphate monobasic buffer",
        "cysteine HCl reducing agent",
        "resazurin anaerobic indicator",
        "sodium acetate standard HPLC",
        "acetate ion chromatography",
        "methyl viologen electron mediator",
        "riboflavin electron shuttle",
        "MES medium Sporomusa",
        "headspace gas chromatography",
        "CO2 cylinder purity 99.9",
        "N2 CO2 mixed gas anaerobic",
        "tungsten wire electrode",
        "potentiostat three electrode cell",
        "reference electrode Ag AgCl",
        "proton exchange membrane Nafion",
        "acetate assay enzymatic kit",
    ],
}

# ── Protocol search topics — much broader to get thousands of entries ────────

# Topics are grouped by domain but deliberately broad to maximise hits
PROTOCOL_TOPICS = {
    "cell_biology": [
        "cryopreservation",
        "trehalose cryoprotection",
        "cell viability assay",
        "HeLa cell culture",
        "DMSO freezing protocol",
        "post-thaw cell recovery",
        "trypan blue exclusion",
        "mammalian cell transfection",
        "lentiviral transduction",
        "CRISPR Cas9 cell line",
        "cell proliferation assay",
        "apoptosis detection annexin",
        "flow cytometry staining",
        "immunofluorescence microscopy",
        "confocal microscopy fixation",
        "Western blot protein",
        "protein extraction mammalian",
        "co-immunoprecipitation",
        "chromatin immunoprecipitation ChIP",
        "RNA extraction cells",
        "qPCR gene expression",
        "cell migration scratch assay",
        "invasion Matrigel assay",
        "colony formation assay",
        "cell cycle analysis",
        "mitochondrial membrane potential",
        "reactive oxygen species ROS",
        "autophagy LC3 detection",
        "lysosome staining LysoTracker",
        "endosome trafficking",
    ],
    "gut_health": [
        "FITC dextran permeability",
        "intestinal permeability assay",
        "tight junction protein",
        "probiotic mouse gavage",
        "claudin occludin immunostaining",
        "colon tissue histology",
        "intestinal organoid culture",
        "Caco-2 monolayer TEER",
        "transepithelial resistance measurement",
        "mucus layer quantification",
        "goblet cell staining",
        "gut microbiome 16S sequencing",
        "fecal transplant mouse",
        "germ-free mouse colonization",
        "SCFA short chain fatty acid",
        "butyrate intestinal epithelial",
        "LPS inflammatory challenge",
        "IL-6 ELISA intestinal",
        "TNF-alpha cytokine measurement",
        "colon explant culture",
        "dextran sodium sulfate colitis",
        "TNBS colitis model",
        "inflammatory bowel disease model",
        "mucin glycoprotein staining",
        "ileum jejunum tissue section",
    ],
    "diagnostics": [
        "electrochemical biosensor",
        "antibody functionalized electrode",
        "differential pulse voltammetry",
        "cyclic voltammetry",
        "impedance spectroscopy biosensor",
        "lateral flow immunoassay",
        "paper-based analytical device",
        "gold nanoparticle biosensor",
        "ELISA sandwich immunoassay",
        "surface plasmon resonance",
        "fluorescence immunoassay",
        "quartz crystal microbalance",
        "microfluidic immunoassay",
        "aptamer biosensor",
        "molecularly imprinted polymer",
        "point of care diagnostics",
        "blood glucose sensor",
        "CRP detection immunosensor",
        "troponin cardiac biosensor",
        "IL-6 cytokine sensor",
        "nucleic acid amplification LAMP",
        "qPCR diagnostic assay",
        "digital PCR quantification",
        "CRISPR diagnostic Cas12",
        "colorimetric detection assay",
    ],
    "climate": [
        "microbial electrosynthesis",
        "bioelectrochemical system",
        "CO2 reduction microbial",
        "Sporomusa ovata culture",
        "anaerobic cultivation technique",
        "cathode potential bioelectrochemical",
        "acetate production electrosynthesis",
        "biocathode electrode preparation",
        "carbon capture biological",
        "electrode biofilm formation",
        "cyclic voltammetry microbial",
        "chronoamperometry bioelectrochemical",
        "coulombic efficiency calculation",
        "HPLC organic acid analysis",
        "ion chromatography acetate",
        "gas chromatography headspace",
        "anaerobic chamber technique",
        "strict anaerobe handling",
        "methanogen inhibition 2-bromoethanesulfonate",
        "Geobacter sulfurreducens electrode",
        "Clostridium aceticum culture",
    ],
    # Broader biology to get volume
    "genomics": [
        "DNA extraction genomic",
        "RNA extraction TRIzol",
        "PCR amplification",
        "qPCR SYBR green",
        "RT-PCR reverse transcription",
        "gel electrophoresis agarose",
        "plasmid DNA purification miniprep",
        "maxiprep plasmid purification",
        "restriction enzyme digestion",
        "ligation cloning",
        "bacterial transformation",
        "Gibson assembly cloning",
        "Golden Gate assembly",
        "site-directed mutagenesis",
        "Sanger sequencing preparation",
        "next generation sequencing library",
        "ChIP sequencing",
        "ATAC sequencing chromatin",
        "single cell RNA sequencing",
        "spatial transcriptomics",
    ],
    "proteomics": [
        "protein gel SDS-PAGE",
        "Western blot transfer",
        "ELISA direct indirect",
        "mass spectrometry sample preparation",
        "protein purification His-tag",
        "GST pulldown protein interaction",
        "protein crystallization hanging drop",
        "size exclusion chromatography protein",
        "affinity chromatography purification",
        "dialysis protein buffer exchange",
        "Bradford protein quantification",
        "BCA protein assay",
        "dot blot protein detection",
        "native PAGE electrophoresis",
        "2D gel electrophoresis proteomics",
        "SILAC metabolic labeling",
        "iTRAQ quantitative proteomics",
        "crosslinking mass spectrometry",
        "hydrogen deuterium exchange HDX",
        "surface plasmon resonance binding",
    ],
    "immunology": [
        "flow cytometry immunophenotyping",
        "PBMC isolation Ficoll",
        "T cell activation stimulation",
        "B cell ELISPOT assay",
        "cytokine multiplex Luminex",
        "macrophage polarization M1 M2",
        "dendritic cell maturation",
        "NK cell cytotoxicity assay",
        "complement activation assay",
        "antibody isotyping ELISA",
        "immunohistochemistry tissue",
        "cytokine intracellular staining",
        "regulatory T cell Treg",
        "neutrophil NET formation",
        "phagocytosis assay",
    ],
    "microbiology": [
        "bacterial culture growth curve",
        "antibiotic MIC determination",
        "biofilm formation assay",
        "colony counting serial dilution",
        "competent cell preparation",
        "electroporation bacteria",
        "yeast transformation",
        "fungal culture protocol",
        "mycoplasma testing PCR",
        "virus titration plaque assay",
        "virus purification ultracentrifugation",
        "ELISA viral antigen",
        "antimicrobial susceptibility testing",
        "minimal bactericidal concentration",
        "quorum sensing assay",
    ],
}

# ── PubMed queries per domain (more specific for better abstracts) ───────────

PUBMED_QUERIES = {
    "cell_biology": [
        "trehalose cryopreservation mammalian cells viability",
        "DMSO-free cryoprotection cell line",
        "post-thaw cell recovery protocol optimization",
        "HeLa cell cryogenic storage",
        "vitrification mammalian cell cryopreservation",
        "cell membrane stabilization cryoprotectant",
        "sugar cryoprotection intracellular",
        "slow cooling cryopreservation protocol",
        "liquid nitrogen cell storage optimal",
        "cryovial seeding density recovery",
    ],
    "gut_health": [
        "Lactobacillus rhamnosus GG intestinal permeability mouse",
        "FITC-dextran gut barrier tight junction",
        "claudin-1 occludin gut epithelium probiotic",
        "intestinal barrier function assessment in vivo",
        "Caco-2 monolayer permeability TEER measurement",
        "tight junction protein expression probiotic supplementation",
        "gut microbiome dysbiosis intestinal permeability",
        "dextran sodium sulfate colitis barrier function",
        "short chain fatty acid butyrate intestinal epithelial",
        "mucus layer gut protection probiotic",
    ],
    "diagnostics": [
        "paper-based electrochemical biosensor C-reactive protein",
        "anti-CRP antibody gold nanoparticle detection",
        "point-of-care CRP detection whole blood sensitivity",
        "electrochemical immunosensor CRP limit of detection",
        "screen-printed electrode functionalization antibody",
        "differential pulse voltammetry immunosensor",
        "lateral flow assay CRP rapid test",
        "microfluidic immunoassay inflammatory marker",
        "impedance biosensor protein detection",
        "gold electrode SAM antibody immobilization",
    ],
    "climate": [
        "Sporomusa ovata bioelectrochemical CO2 reduction acetate",
        "microbial electrosynthesis cathode potential current density",
        "bioelectrochemical system carbon capture rate",
        "autotrophic acetogenesis CO2 fixation electrode",
        "biocathode microorganism extracellular electron transfer",
        "acetate production bioelectrochemical faradaic efficiency",
        "direct electron transfer acetogens electrode",
        "CO2 fixation rate bioelectrochemical acetate yield",
        "microbial electrosynthesis scale-up reactor design",
        "cathode biofilm formation electron donor",
    ],
    "genomics": [
        "CRISPR Cas9 genome editing efficiency",
        "RNA extraction quality assessment protocol",
        "single cell RNA sequencing library preparation",
        "ChIP-seq protocol optimization histone",
        "ATAC-seq chromatin accessibility protocol",
        "digital PCR absolute quantification",
        "multiplex qPCR assay design validation",
        "LAMP isothermal amplification diagnostic",
        "nanopore sequencing library protocol",
        "whole genome sequencing library preparation",
    ],
    "proteomics": [
        "Western blot quantification normalization",
        "protein-protein interaction co-immunoprecipitation",
        "proximity ligation assay protein interaction",
        "ELISA sensitivity optimization protocol",
        "mass spectrometry proteomics sample preparation",
        "affinity purification protein complex",
        "surface plasmon resonance binding kinetics",
        "isothermal titration calorimetry protein binding",
        "thermal shift assay protein stability",
        "AlphaFold protein structure prediction validation",
    ],
}

# ── Source-specific query optimisation ──────────────────────────────────────

# protocols.io responds best to 1-3 word queries
PROTOCOLS_IO_TOPICS = []
for domain_topics in PROTOCOL_TOPICS.values():
    for t in domain_topics:
        # shorten to first 3 words
        short = " ".join(t.split()[:3])
        if short not in PROTOCOLS_IO_TOPICS:
            PROTOCOLS_IO_TOPICS.append(short)

# Bio-protocol and Nature Protocols work with longer queries
LITERATURE_PROTOCOL_TOPICS = [
    topic for topics in PROTOCOL_TOPICS.values() for topic in topics
]

# ── Cookie template (users fill in their browser cookies) ───────────────────

COOKIE_FILE = "cookies.json"   # relative to scrapers/ dir

# Domains that benefit from cookies (paywalls / rate limits)
COOKIED_DOMAINS = {
    "jove.com": [],        # jove requires login for full access
    "nature.com": [],      # nature.com rate-limits heavy scraping
    "protocols.io": [],    # already have token but cookie is fallback
}

# ── Allowed supplier domains for URL validation ──────────────────────────────

ALLOWED_SUPPLIER_DOMAINS = [
    "sigmaaldrich.com", "thermofisher.com", "atcc.org",
    "addgene.org", "promega.com", "qiagen.com", "neb.com",
    "bio-rad.com", "abcam.com", "rndsystems.com", "idtdna.com",
    "fishersci.com", "merckgroup.com", "emdmillipore.com",
    "cellsignal.com", "stemcell.com", "lonza.com", "bd.com",
    "sartorius.com", "cytiva.com", "gelifesciences.com",
]

ALLOWED_PROTOCOL_DOMAINS = [
    "protocols.io", "bio-protocol.org", "nature.com",
    "jove.com", "openwetware.org", "promega.com",
    "qiagen.com", "idtdna.com", "addgene.org",
    "pubmed.ncbi.nlm.nih.gov", "biorxiv.org", "arxiv.org",
    "atcc.org", "bio-rad.com", "neb.com",
]
